# aux.py
#
# Top 50 websites in Spain (public Similarweb list) as of scrape time.
# Ordered list of domains for default/testing purposes.

TOP_ES_WEBS: list[str] = [
    "google.com",
    "youtube.com",
    "marca.com",
    "chatgpt.com",
    "facebook.com",
    "instagram.com",
    "x.com",
    "amazon.es",
    "whatsapp.com",
    "as.com",
    "elmundo.es",
    "wikipedia.org",
    "elpais.com",
    "bing.com",
    "mundodeportivo.com",
    "sport.es",
    "live.com",
    "20minutos.es",
    "twitch.tv",
    "tiktok.com",
    "aemet.es",
    "idealista.com",
    "aliexpress.com",
    "temu.com",
    "xvideos.com",
    "okdiario.com",
    "yahoo.com",
    "linkedin.com",
    "netflix.com",
    "eldiario.es",
    "elconfidencial.com",
    "eltiempo.es",
    "xhamster.com",
    "google.es",
    "elespanol.com",
    "larazon.es",
    "reddit.com",
    "abc.es",
    "infobae.com",
    "pornhub.com",
    "eldebate.com",
    "xvideos.es",
    "microsoft.com",
    "office.com",
    "lavozdegalicia.es",
    "weather.com",
    "share.google",
    "canva.com",
    "lavanguardia.com",
    "booking.com",
]
