# default_dns.py
#
# Default DNS entries shipped with the application.
# Keep values in English and only include resolvers that work out of the box.

from __future__ import annotations

from typing import TypedDict


class DefaultDnsEntry(TypedDict):
    """Structure used by the bundled DNS catalog."""

    id: str
    provider_name: str
    profile_name: str
    regions: list[str]
    target: str
    transport: str
    tls_hostname: str | None
    doh_method: str


# Bundled resolver entries use stable IDs so users can hide a default entry permanently.
DEFAULT_DNS: list[DefaultDnsEntry] = [
    {
        "id": "cloudflare-do53",
        "provider_name": "Cloudflare",
        "profile_name": "Default",
        "regions": ["US"],
        "target": "1.1.1.1",
        "transport": "Do53",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "cloudflare-dot",
        "provider_name": "Cloudflare",
        "profile_name": "Default",
        "regions": ["US"],
        "target": "one.one.one.one",
        "transport": "DoT",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "cloudflare-doh",
        "provider_name": "Cloudflare",
        "profile_name": "Default",
        "regions": ["US"],
        "target": "https://cloudflare-dns.com/dns-query",
        "transport": "DoH",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "cloudflare-malware-do53",
        "provider_name": "Cloudflare",
        "profile_name": "Malware Blocking",
        "regions": ["US"],
        "target": "1.1.1.2",
        "transport": "Do53",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "cloudflare-malware-dot",
        "provider_name": "Cloudflare",
        "profile_name": "Malware Blocking",
        "regions": ["US"],
        "target": "security.cloudflare-dns.com",
        "transport": "DoT",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "cloudflare-malware-doh",
        "provider_name": "Cloudflare",
        "profile_name": "Malware Blocking",
        "regions": ["US"],
        "target": "https://security.cloudflare-dns.com/dns-query",
        "transport": "DoH",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "cloudflare-family-do53",
        "provider_name": "Cloudflare",
        "profile_name": "Malware + Adult Content Blocking",
        "regions": ["US"],
        "target": "1.1.1.3",
        "transport": "Do53",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "cloudflare-family-dot",
        "provider_name": "Cloudflare",
        "profile_name": "Malware + Adult Content Blocking",
        "regions": ["US"],
        "target": "family.cloudflare-dns.com",
        "transport": "DoT",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "cloudflare-family-doh",
        "provider_name": "Cloudflare",
        "profile_name": "Malware + Adult Content Blocking",
        "regions": ["US"],
        "target": "https://family.cloudflare-dns.com/dns-query",
        "transport": "DoH",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "dns4eu-protective-do53",
        "provider_name": "DNS4EU",
        "profile_name": "Protective",
        "regions": ["EU", "CZ"],
        "target": "86.54.11.1",
        "transport": "Do53",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "dns4eu-protective-dot",
        "provider_name": "DNS4EU",
        "profile_name": "Protective",
        "regions": ["EU", "CZ"],
        "target": "protective.joindns4.eu",
        "transport": "DoT",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "dns4eu-protective-doh",
        "provider_name": "DNS4EU",
        "profile_name": "Protective",
        "regions": ["EU", "CZ"],
        "target": "https://protective.joindns4.eu/dns-query",
        "transport": "DoH",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "dns4eu-child-do53",
        "provider_name": "DNS4EU",
        "profile_name": "Protective + Child Protection",
        "regions": ["EU", "CZ"],
        "target": "86.54.11.12",
        "transport": "Do53",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "dns4eu-child-dot",
        "provider_name": "DNS4EU",
        "profile_name": "Protective + Child Protection",
        "regions": ["EU", "CZ"],
        "target": "child.joindns4.eu",
        "transport": "DoT",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "dns4eu-child-doh",
        "provider_name": "DNS4EU",
        "profile_name": "Protective + Child Protection",
        "regions": ["EU", "CZ"],
        "target": "https://child.joindns4.eu/dns-query",
        "transport": "DoH",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "dns4eu-noads-do53",
        "provider_name": "DNS4EU",
        "profile_name": "Protective + Ad Blocking",
        "regions": ["EU", "CZ"],
        "target": "86.54.11.13",
        "transport": "Do53",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "dns4eu-child-noads-do53",
        "provider_name": "DNS4EU",
        "profile_name": "Protective + Child Protection + Ad Blocking",
        "regions": ["EU", "CZ"],
        "target": "86.54.11.11",
        "transport": "Do53",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "dns4eu-child-noads-dot",
        "provider_name": "DNS4EU",
        "profile_name": "Protective + Child Protection + Ad Blocking",
        "regions": ["EU", "CZ"],
        "target": "child-noads.joindns4.eu",
        "transport": "DoT",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "dns4eu-child-noads-doh",
        "provider_name": "DNS4EU",
        "profile_name": "Protective + Child Protection + Ad Blocking",
        "regions": ["EU", "CZ"],
        "target": "https://child-noads.joindns4.eu/dns-query",
        "transport": "DoH",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "dns4eu-noads-dot",
        "provider_name": "DNS4EU",
        "profile_name": "Protective + Ad Blocking",
        "regions": ["EU", "CZ"],
        "target": "noads.joindns4.eu",
        "transport": "DoT",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "dns4eu-noads-doh",
        "provider_name": "DNS4EU",
        "profile_name": "Protective + Ad Blocking",
        "regions": ["EU", "CZ"],
        "target": "https://noads.joindns4.eu/dns-query",
        "transport": "DoH",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "quad9-default",
        "provider_name": "Quad9",
        "profile_name": "Recommended",
        "regions": ["EU", "CH"],
        "target": "9.9.9.9",
        "transport": "Do53",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "quad9-default-dot",
        "provider_name": "Quad9",
        "profile_name": "Recommended",
        "regions": ["EU", "CH"],
        "target": "dns.quad9.net",
        "transport": "DoT",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "quad9-default-doh",
        "provider_name": "Quad9",
        "profile_name": "Recommended",
        "regions": ["EU", "CH"],
        "target": "https://dns.quad9.net/dns-query",
        "transport": "DoH",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "nextdns-default",
        "provider_name": "NextDNS",
        "profile_name": "Default",
        "regions": ["US"],
        "target": "45.90.28.0",
        "transport": "Do53",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "controld-unfiltered-do53",
        "provider_name": "ControlD",
        "profile_name": "Unfiltered",
        "regions": ["CA"],
        "target": "76.76.2.0",
        "transport": "Do53",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "controld-unfiltered-dot",
        "provider_name": "ControlD",
        "profile_name": "Unfiltered",
        "regions": ["CA"],
        "target": "p0.freedns.controld.com",
        "transport": "DoT",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "controld-unfiltered-doh",
        "provider_name": "ControlD",
        "profile_name": "Unfiltered",
        "regions": ["CA"],
        "target": "https://freedns.controld.com/p0",
        "transport": "DoH",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "controld-ads-do53",
        "provider_name": "ControlD",
        "profile_name": "Ads & Tracking",
        "regions": ["CA"],
        "target": "76.76.2.2",
        "transport": "Do53",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "controld-ads-dot",
        "provider_name": "ControlD",
        "profile_name": "Ads & Tracking",
        "regions": ["CA"],
        "target": "p2.freedns.controld.com",
        "transport": "DoT",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "controld-ads-doh",
        "provider_name": "ControlD",
        "profile_name": "Ads & Tracking",
        "regions": ["CA"],
        "target": "https://freedns.controld.com/p2",
        "transport": "DoH",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "controld-family-do53",
        "provider_name": "ControlD",
        "profile_name": "Family Friendly",
        "regions": ["CA"],
        "target": "76.76.2.4",
        "transport": "Do53",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "controld-family-dot",
        "provider_name": "ControlD",
        "profile_name": "Family Friendly",
        "regions": ["CA"],
        "target": "family.freedns.controld.com",
        "transport": "DoT",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "controld-family-doh",
        "provider_name": "ControlD",
        "profile_name": "Family Friendly",
        "regions": ["CA"],
        "target": "https://freedns.controld.com/family",
        "transport": "DoH",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "controld-oisd-do53",
        "provider_name": "ControlD",
        "profile_name": "OISD Full",
        "regions": ["CA"],
        "target": "76.76.2.32",
        "transport": "Do53",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "controld-oisd-dot",
        "provider_name": "ControlD",
        "profile_name": "OISD Full",
        "regions": ["CA"],
        "target": "x-oisd.freedns.controld.com",
        "transport": "DoT",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "controld-oisd-doh",
        "provider_name": "ControlD",
        "profile_name": "OISD Full",
        "regions": ["CA"],
        "target": "https://freedns.controld.com/x-oisd",
        "transport": "DoH",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "mullvad-base-dot",
        "provider_name": "Mullvad",
        "profile_name": "Base",
        "regions": ["EU", "SE"],
        "target": "194.242.2.4",
        "transport": "DoT",
        "tls_hostname": "base.dns.mullvad.net",
        "doh_method": "POST",
    },
    {
        "id": "mullvad-base-doh",
        "provider_name": "Mullvad",
        "profile_name": "Base",
        "regions": ["EU", "SE"],
        "target": "https://base.dns.mullvad.net/dns-query",
        "transport": "DoH",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "mullvad-adblock-dot",
        "provider_name": "Mullvad",
        "profile_name": "Ad Blocking",
        "regions": ["EU", "SE"],
        "target": "194.242.2.3",
        "transport": "DoT",
        "tls_hostname": "adblock.dns.mullvad.net",
        "doh_method": "POST",
    },
    {
        "id": "mullvad-adblock-doh",
        "provider_name": "Mullvad",
        "profile_name": "Ad Blocking",
        "regions": ["EU", "SE"],
        "target": "https://adblock.dns.mullvad.net/dns-query",
        "transport": "DoH",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "mullvad-default-dot",
        "provider_name": "Mullvad",
        "profile_name": "Default",
        "regions": ["EU", "SE"],
        "target": "194.242.2.2",
        "transport": "DoT",
        "tls_hostname": "dns.mullvad.net",
        "doh_method": "POST",
    },
    {
        "id": "mullvad-default-doh",
        "provider_name": "Mullvad",
        "profile_name": "Default",
        "regions": ["EU", "SE"],
        "target": "https://dns.mullvad.net/dns-query",
        "transport": "DoH",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "mullvad-extended-dot",
        "provider_name": "Mullvad",
        "profile_name": "Extended",
        "regions": ["EU", "SE"],
        "target": "194.242.2.5",
        "transport": "DoT",
        "tls_hostname": "extended.dns.mullvad.net",
        "doh_method": "POST",
    },
    {
        "id": "mullvad-extended-doh",
        "provider_name": "Mullvad",
        "profile_name": "Extended",
        "regions": ["EU", "SE"],
        "target": "https://extended.dns.mullvad.net/dns-query",
        "transport": "DoH",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "mullvad-family-dot",
        "provider_name": "Mullvad",
        "profile_name": "Family",
        "regions": ["EU", "SE"],
        "target": "194.242.2.6",
        "transport": "DoT",
        "tls_hostname": "family.dns.mullvad.net",
        "doh_method": "POST",
    },
    {
        "id": "mullvad-family-doh",
        "provider_name": "Mullvad",
        "profile_name": "Family",
        "regions": ["EU", "SE"],
        "target": "https://family.dns.mullvad.net/dns-query",
        "transport": "DoH",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "mullvad-all-dot",
        "provider_name": "Mullvad",
        "profile_name": "All Content Blocking",
        "regions": ["EU", "SE"],
        "target": "194.242.2.9",
        "transport": "DoT",
        "tls_hostname": "all.dns.mullvad.net",
        "doh_method": "POST",
    },
    {
        "id": "mullvad-all-doh",
        "provider_name": "Mullvad",
        "profile_name": "All Content Blocking",
        "regions": ["EU", "SE"],
        "target": "https://all.dns.mullvad.net/dns-query",
        "transport": "DoH",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "gcore-default",
        "provider_name": "Gcore",
        "profile_name": "Default",
        "regions": ["EU", "LU"],
        "target": "95.85.95.85",
        "transport": "Do53",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "flashstart-default",
        "provider_name": "FlashStart",
        "profile_name": "Default",
        "regions": ["EU", "IT"],
        "target": "185.236.104.104",
        "transport": "Do53",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "google-default",
        "provider_name": "Google",
        "profile_name": "Default",
        "regions": ["US"],
        "target": "8.8.8.8",
        "transport": "Do53",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "google-default-dot",
        "provider_name": "Google",
        "profile_name": "Default",
        "regions": ["US"],
        "target": "dns.google",
        "transport": "DoT",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "google-default-doh",
        "provider_name": "Google",
        "profile_name": "Default",
        "regions": ["US"],
        "target": "https://dns.google/dns-query",
        "transport": "DoH",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "dns4eu-default",
        "provider_name": "DNS4EU",
        "profile_name": "Unfiltered",
        "regions": ["EU", "CZ"],
        "target": "86.54.11.100",
        "transport": "Do53",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "dns4eu-default-dot",
        "provider_name": "DNS4EU",
        "profile_name": "Unfiltered",
        "regions": ["EU", "CZ"],
        "target": "unfiltered.joindns4.eu",
        "transport": "DoT",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "dns4eu-default-doh",
        "provider_name": "DNS4EU",
        "profile_name": "Unfiltered",
        "regions": ["EU", "CZ"],
        "target": "https://unfiltered.joindns4.eu/dns-query",
        "transport": "DoH",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "adguard-default-do53",
        "provider_name": "AdGuard",
        "profile_name": "Default",
        "regions": ["EU", "CY"],
        "target": "94.140.14.14",
        "transport": "Do53",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "adguard-default-dot",
        "provider_name": "AdGuard",
        "profile_name": "Default",
        "regions": ["EU", "CY"],
        "target": "dns.adguard-dns.com",
        "transport": "DoT",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "adguard-default-doh",
        "provider_name": "AdGuard",
        "profile_name": "Default",
        "regions": ["EU", "CY"],
        "target": "https://dns.adguard-dns.com/dns-query",
        "transport": "DoH",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "adguard-non-filtering-do53",
        "provider_name": "AdGuard",
        "profile_name": "Non-filtering",
        "regions": ["EU", "CY"],
        "target": "94.140.14.140",
        "transport": "Do53",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "adguard-non-filtering-dot",
        "provider_name": "AdGuard",
        "profile_name": "Non-filtering",
        "regions": ["EU", "CY"],
        "target": "unfiltered.adguard-dns.com",
        "transport": "DoT",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "adguard-non-filtering-doh",
        "provider_name": "AdGuard",
        "profile_name": "Non-filtering",
        "regions": ["EU", "CY"],
        "target": "https://unfiltered.adguard-dns.com/dns-query",
        "transport": "DoH",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "adguard-family-do53",
        "provider_name": "AdGuard",
        "profile_name": "Family Protection",
        "regions": ["EU", "CY"],
        "target": "94.140.14.15",
        "transport": "Do53",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "adguard-family-dot",
        "provider_name": "AdGuard",
        "profile_name": "Family Protection",
        "regions": ["EU", "CY"],
        "target": "family.adguard-dns.com",
        "transport": "DoT",
        "tls_hostname": None,
        "doh_method": "POST",
    },
    {
        "id": "adguard-family-doh",
        "provider_name": "AdGuard",
        "profile_name": "Family Protection",
        "regions": ["EU", "CY"],
        "target": "https://family.adguard-dns.com/dns-query",
        "transport": "DoH",
        "tls_hostname": None,
        "doh_method": "POST",
    },
]
